name: Delete Old Firestore Saves
on:
  schedule:
    - cron: '0 2 * * 0' # Sonntags um 02:00 UTC
  workflow_dispatch: # Optional: manuell auslösbar
    inputs:
      days:
        description: 'Anzahl der Tage vor dem Löschen'
        required: false
        default: '7'
      
env:
  NODE_ENV: production

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run cleanup script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          RETENTION_DAYS: ${{ github.event.inputs.days || '7' }}
        run: node scripts/deleteOldSaves.js
