name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - beta

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            firebase deploy --only hosting:production
          elif [[ "${GITHUB_REF}" == "refs/heads/beta" ]]; then
            firebase deploy --only hosting:beta
          fi